-- Query de los company codes
SELECT A.COMPANY_CODE, A.FOUNDER, B.TOT_LEAD_MGR, C.TOT_SR_MGR, D.TOT_MGR, E.TOT_EMP
FROM
(SELECT DISTINCT COMPANY_CODE, FOUNDER
FROM COMPANY) A,
(SELECT COMPANY_CODE, COUNT(DISTINCT LEAD_MANAGER_CODE) AS TOT_LEAD_MGR
FROM LEAD_MANAGER
GROUP BY COMPANY_CODE) B,
(SELECT COMPANY_CODE, COUNT(DISTINCT SENIOR_MANAGER_CODE) AS TOT_SR_MGR
FROM SENIOR_MANAGER
GROUP BY COMPANY_CODE) C,
(SELECT COMPANY_CODE, COUNT(DISTINCT MANAGER_CODE) AS TOT_MGR
FROM MANAGER
GROUP BY COMPANY_CODE) D,
(SELECT COMPANY_CODE, COUNT(DISTINCT EMPLOYEE_CODE) AS TOT_EMP
FROM EMPLOYEE
GROUP BY COMPANY_CODE) E
WHERE
B.COMPANY_CODE = A.COMPANY_CODE
AND C.COMPANY_CODE = A.COMPANY_CODE
AND D.COMPANY_CODE = A.COMPANY_CODE
AND E.COMPANY_CODE = A.COMPANY_CODE
ORDER BY A.COMPANY_CODE;