-- Professions in pivot table
SELECT NAME_A AS Doctor, NAME_B AS Professor, NAME_C AS Singer, NAME_D AS Actor
FROM
(SELECT NAME_A, ROWNUM AS ROWNUM_A
FROM
(SELECT NAME NAME_A
FROM OCCUPATIONS
WHERE OCCUPATION = 'Doctor'
ORDER BY NAME)) A,
(SELECT NAME_B, ROWNUM AS ROWNUM_B
FROM
(SELECT NAME AS NAME_B
FROM OCCUPATIONS
WHERE OCCUPATION = 'Professor'
ORDER BY NAME)) B,
(SELECT NAME_C, ROWNUM AS ROWNUM_C
FROM
(SELECT NAME AS NAME_C
FROM OCCUPATIONS
WHERE OCCUPATION = 'Singer'
ORDER BY NAME)) C,
(SELECT NAME_D, ROWNUM AS ROWNUM_D
FROM
(SELECT NAME AS NAME_D
FROM OCCUPATIONS
WHERE OCCUPATION = 'Actor'
ORDER BY NAME)) D
WHERE A.ROWNUM_A (+)= B.ROWNUM_B
AND B.ROWNUM_B = C.ROWNUM_C(+)
AND C.ROWNUM_C = D.ROWNUM_D(+)
ORDER BY B.ROWNUM_B;