-- Median value for STATION table
SELECT
    CASE
        WHEN MOD(TOT_REC,2) = 0 THEN ROUND((MX+MN)/2,4)
        ELSE ROUND(ME,4)
    END MEDIA    
FROM
(SELECT MAX(LAT_N) AS MX
FROM
(SELECT COUNT(*) TOT_REC FROM STATION) A,
(SELECT LAT_N, ROWNUM AS ROWNUM_A 
FROM
(SELECT LAT_N
FROM STATION ORDER BY LAT_N)) B
WHERE ROWNUM_A <= TOT_REC/2) A,
(SELECT MIN(LAT_N) AS MN
FROM
(SELECT COUNT(*) TOT_REC FROM STATION) A,
(SELECT LAT_N, ROWNUM AS ROWNUM_B 
FROM
(SELECT LAT_N
FROM
STATION ORDER BY LAT_N)) B
WHERE ROWNUM_B > TOT_REC/2 AND ROWNUM_B < TOT_REC) B,
(SELECT LAT_N AS ME
FROM
(SELECT COUNT(*) TOT_REC FROM STATION) A,
(SELECT LAT_N, ROWNUM AS ROWNUM_C 
FROM
(SELECT LAT_N
FROM 
STATION ORDER BY LAT_N)) C
WHERE ROWNUM_C = CEIL(TOT_REC/2)) C,
(SELECT COUNT(*) AS TOT_REC FROM STATION) D;